vich_uploader:
    db_driver: orm

    mappings:
        contents:
            uri_prefix: /contents
            upload_destination: '%kernel.project_dir%/public/contents'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
